/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author David
 */
public class AdminLänder extends javax.swing.JFrame {
    private InfDB idb;
    private boolean arAdmin;
    private ArrayList<String> bortagnaLid = new ArrayList<>();

    public AdminLänder(InfDB idb, boolean arAdmin) {
        this.idb = idb;
        this.arAdmin = arAdmin;
        initComponents();
        
        fyllTabell();
    }
    private void fyllTabell() {
        String[] kolumnNamn = {"ID", "Namn", "Språk", "Valuta", "Tidszon", "Politisk struktur", "Ekonomi"};
        
        // Vi nollställer modellen varje gång vi fyller den för att undvika dublering vid till lägg av nytt land 
        DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return arAdmin && column != 0;
            }
        };
        
        tblLander.setModel(model);
        
        try {
            String sql = "SELECT * FROM land";
            ArrayList<HashMap<String, String>> allaLander = idb.fetchRows(sql);
            
            if(allaLander != null) {
                for(HashMap<String, String> rad : allaLander) {
                    String[] dataRad = {
                        rad.get("lid"),
                        rad.get("namn"),
                        rad.get("sprak"),
                        rad.get("valuta"),
                        rad.get("tidszon"),
                        rad.get("politisk_struktur"),
                        rad.get("ekonomi")
                    };
                    model.addRow(dataRad);
                }
            }
        } catch(InfException ex) {
            System.out.println("Fel vid hämtning av länder: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLander = new javax.swing.JTable();
        btnSpara = new javax.swing.JButton();
        btnNyttLand = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblLander.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tblLander);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnNyttLand.setText("Lägg till land");
        btnNyttLand.addActionListener(this::btnNyttLandActionPerformed);

        btnTaBort.setText("Ta bort land");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1527, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNyttLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnNyttLand)
                    .addComponent(btnTaBort)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyttLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttLandActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLander.getModel();
        
        // Lägger till en tom ny rad i tabellen
        model.addRow(new Object[]{"", "", "", "", "", "", ""});
    }//GEN-LAST:event_btnNyttLandActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:                                       
if (tblLander.isEditing()) {
            tblLander.getCellEditor().stopCellEditing();
        }

        DefaultTableModel model = (DefaultTableModel) tblLander.getModel();
        int antalRader = model.getRowCount();

        try {
            
            // Först - radera länder som markerats för borttagning
                for (String lid : bortagnaLid) {
                String sqlTaBort = "DELETE FROM land WHERE lid = " + lid;
                idb.delete(sqlTaBort);
                }
                bortagnaLid.clear();
            
            for (int i = 0; i < antalRader; i++) {
                
                // Hämta alla fält från raden
                String lid = model.getValueAt(i, 0).toString();
                String namn = model.getValueAt(i, 1).toString();
                String sprak = model.getValueAt(i, 2).toString();
                String valuta = model.getValueAt(i, 3).toString();
                String tidszon = model.getValueAt(i, 4).toString();
                String politisk = model.getValueAt(i, 5).toString();
                String ekonomi = model.getValueAt(i, 6).toString();

                // om ID-fältet är tomt, betyder "Lägg till" kanppen har används
                if(lid.isEmpty()) {
                    
                    // Räkna nästa lediga id
                    String nyttId = idb.getAutoIncrement("land", "lid");
                    
                    // INSERT fråga nytt landet
                    String sqlInsert = "INSERT INTO land VALUES (" +
                            nyttId + ", '" + namn + "', '" + sprak + "', " + valuta + ", '" + 
                            tidszon + "', '" + politisk + "', '" + ekonomi + "')";
                    
                    // Spara nytt land
                    idb.insert(sqlInsert);
                    
                    // Uppdatera tabellen
                    model.setValueAt(nyttId, i, 0);
                    
                } else {
                    // Om ID finns
                    String sqlUppdatera = "UPDATE land SET " +
                            "namn = '" + namn + "', " +
                            "sprak = '" + sprak + "', " +
                            "valuta = " + valuta + ", " + 
                            "tidszon = '" + tidszon + "', " +
                            "politisk_struktur = '" + politisk + "', " +
                            "ekonomi = '" + ekonomi + "' " +
                            "WHERE lid = " + lid;

                    idb.update(sqlUppdatera);
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna och nya länder har sparats!");

        } catch (InfException ex) {
            System.out.println("Fel vid uppdatering av länder: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte spara. Kolla så att valutan skrivs med punkt (t.ex. 10.5).");        
    }//GEN-LAST:event_btnSparaActionPerformed
    }
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        int valdRad = tblLander.getSelectedRow();
    
    if (valdRad == -1) {
        JOptionPane.showMessageDialog(this, "Markera ett land att ta bort först.");
        return;
    }
    
    DefaultTableModel model = (DefaultTableModel) tblLander.getModel();
    
    // Spara lid i listan över borttagna - sparas i databasen vid spara
    Object lidVarde = model.getValueAt(valdRad, 0);
    if (lidVarde != null && !lidVarde.toString().isEmpty()) {
        bortagnaLid.add(lidVarde.toString());
    }
    
    model.removeRow(valdRad);
    }//GEN-LAST:event_btnTaBortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyttLand;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLander;
    // End of variables declaration//GEN-END:variables

}
