/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nikla
 */
public class AdminPartners extends javax.swing.JFrame {
    
    private InfDB idb;
    private boolean arAdmin;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPartners.class.getName());

    /**
     * Creates new form AdminPartners
     */

public AdminPartners(InfDB idb, boolean arAdmin) {
        this.idb = idb;
        this.arAdmin = arAdmin;
        initComponents();
        
        fyllTabell();
    }
private void fyllTabell() {
        String[] kolumnNamn = {"ID", "Namn", "Kontaktperson", "E-post", "Telefon", "Adress", "Bransch", "Stad", "Land"};
        
        DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return arAdmin; 
            }
        };
        
      tblAdminPartners.setModel(model);
        
        try {
String sqlFraga = "SELECT * FROM partner";
            ArrayList<HashMap<String, String>> allaPartners = idb.fetchRows(sqlFraga);
            
            if (allaPartners != null) {
                for (HashMap<String, String> rad : allaPartners) {
                    
                    // 2. Vi hämtar ID:t för staden (som ligger i kolumnen 'stad')
                    String stadId = rad.get("stad"); 
                    String stadNamn = "";
                    String landNamn = "";
                    
                    // 3. Om staden finns, slår vi upp vad den heter
                    if(stadId != null) {
                        String sqlStad = "SELECT namn FROM stad WHERE sid = " + stadId;
                        stadNamn = idb.fetchSingle(sqlStad);
                        
                        // Vi hämtar också vilket land (ID) staden tillhör
                        String sqlStadLandID = "SELECT land FROM stad WHERE sid = " + stadId;
                        String landId = idb.fetchSingle(sqlStadLandID);
                        
                        // 4. Om landet finns, slår vi upp vad det heter
                        if(landId != null) {
                            String sqlLand = "SELECT namn FROM land WHERE lid = " + landId;
                            landNamn = idb.fetchSingle(sqlLand);
                        }
                    }
                    
  String[] dataRad = {
                        rad.get("pid"), 
                        rad.get("namn"),        
                        rad.get("kontaktperson"), 
                        rad.get("kontaktepost"), 
                        rad.get("telefon"), 
                        rad.get("adress"), 
                        rad.get("branch"), 
                        stadNamn,                 
                        landNamn                  
                    };
                    
                    model.addRow(dataRad);
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av partners: " + ex.getMessage());
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminPartners = new javax.swing.JTable();
        BtnSpara = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblAdminPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pid", "Namn", "Kontaktperson", "E-post", "Nummer", "Adress", "Branch", "Stad", "Land"
            }
        ));
        jScrollPane1.setViewportView(tblAdminPartners);

        BtnSpara.setText("Spara ändringar");
        BtnSpara.addActionListener(this::BtnSparaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSpara)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSpara))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSparaActionPerformed
        // TODO add your handling code here:
        if (tblAdminPartners.isEditing()) {
            tblAdminPartners.getCellEditor().stopCellEditing();
        }

        DefaultTableModel model = (DefaultTableModel) tblAdminPartners.getModel();
        int antalRader = model.getRowCount();

        try {
            for (int i = 0; i < antalRader; i++) {
                String pid = model.getValueAt(i, 0).toString();
                String namn = model.getValueAt(i, 1).toString();
                String kontaktperson = model.getValueAt(i, 2).toString();
                String epost = model.getValueAt(i, 3).toString();
                String telefon = model.getValueAt(i, 4).toString();
                String adress = model.getValueAt(i, 5).toString();
                String branch = model.getValueAt(i, 6).toString();

                String sqlUppdatera = "UPDATE partner SET " +
                        "namn = '" + namn + "', " +
                        "kontaktperson = '" + kontaktperson + "', " +
                        "kontaktepost = '" + epost + "', " +
                        "telefon = '" + telefon + "', " +
                        "adress = '" + adress + "', " +
                        "branch = '" + branch + "' " +
                        "WHERE pid = " + pid;
                
                idb.update(sqlUppdatera);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna har sparats i databasen!");

        } catch (InfException ex) {
            System.out.println("Fel vid uppdatering av partners: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod när ändringarna skulle sparas.");
        }
    }//GEN-LAST:event_BtnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AdminPartners().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSpara;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdminPartners;
    // End of variables declaration//GEN-END:variables
}
