/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author nikla
 */
public class AdminLänder extends javax.swing.JFrame {
    private InfDB idb;
    private boolean arAdmin;

    public AdminLänder(InfDB idb, boolean arAdmin) {
        this.idb = idb;
        this.arAdmin = arAdmin;
        initComponents();
        
        fyllTabell();
    }
    private void fyllTabell() {
        String[] kolumnNamn = {"ID", "Namn", "Språk", "Valuta", "Tidszon", "Politisk struktur", "Ekonomi"};
        
        // Vi måste nollställa modellen varje gång vi fyller den, 
        // annars dubbleras raderna när vi lägger till ett nytt land och uppdaterar!
        DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return arAdmin && column != 0; // Kolumn 0 (ID) får ALDRIG ändras, databasen sköter ofta det!
            }
        };
        
        tblLander.setModel(model);
        
        try {
            String sql = "SELECT * FROM land";
            ArrayList<HashMap<String, String>> allaLander = idb.fetchRows(sql);
            
            if(allaLander != null) {
                for(HashMap<String, String> rad : allaLander) {
                    String[] dataRad = {
                        rad.get("lid"),
                        rad.get("namn"),
                        rad.get("sprak"),
                        rad.get("valuta"),
                        rad.get("tidszon"),
                        rad.get("politisk_struktur"),
                        rad.get("ekonomi")
                    };
                    model.addRow(dataRad);
                }
            }
        } catch(InfException ex) {
            System.out.println("Fel vid hämtning av länder: " + ex.getMessage());
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminLänder.class.getName());

    /**
     * Creates new form AdminLänder
     */
    public AdminLänder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLander = new javax.swing.JTable();
        btnSpara = new javax.swing.JButton();
        btnNyttLand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblLander.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tblLander);

        btnSpara.setText("Spara ändring");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnNyttLand.setText("Lägg till");
        btnNyttLand.addActionListener(this::btnNyttLandActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1527, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNyttLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnNyttLand)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyttLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttLandActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLander.getModel();
        
        // Lägger till en ny, tom rad i tabellen (7 tomma fält för våra 7 kolumner)
        // Vi lämnar ID-fältet tomt, det fylls i när vi sparar!
        model.addRow(new Object[]{"", "", "", "", "", "", ""});
    }//GEN-LAST:event_btnNyttLandActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:                                       
if (tblLander.isEditing()) {
            tblLander.getCellEditor().stopCellEditing();
        }

        DefaultTableModel model = (DefaultTableModel) tblLander.getModel();
        int antalRader = model.getRowCount();

        try {
            for (int i = 0; i < antalRader; i++) {
                
                // Hämta alla fält från raden
                String lid = model.getValueAt(i, 0).toString();
                String namn = model.getValueAt(i, 1).toString();
                String sprak = model.getValueAt(i, 2).toString();
                String valuta = model.getValueAt(i, 3).toString();
                String tidszon = model.getValueAt(i, 4).toString();
                String politisk = model.getValueAt(i, 5).toString();
                String ekonomi = model.getValueAt(i, 6).toString();

                // Om ID-fältet är tomt (""), betyder det att vi nyss klickade på "Lägg till"
                if(lid.isEmpty()) {
                    
                    // 1. Be databasklassen räkna ut nästa lediga ID
                    String nyttId = idb.getAutoIncrement("land", "lid");
                    
                    // 2. Skapa en INSERT-fråga för det nya landet
                    String sqlInsert = "INSERT INTO land VALUES (" +
                            nyttId + ", '" + namn + "', '" + sprak + "', " + valuta + ", '" + 
                            tidszon + "', '" + politisk + "', '" + ekonomi + "')";
                    
                    // 3. Spara det nya landet!
                    idb.insert(sqlInsert);
                    
                    // 4. Uppdatera tabellen på skärmen så att det nya ID-numret syns direkt
                    model.setValueAt(nyttId, i, 0);
                    
                } else {
                    // Om ID redan fanns, gör vi en vanlig UPDATE precis som förut
                    String sqlUppdatera = "UPDATE land SET " +
                            "namn = '" + namn + "', " +
                            "sprak = '" + sprak + "', " +
                            "valuta = " + valuta + ", " + 
                            "tidszon = '" + tidszon + "', " +
                            "politisk_struktur = '" + politisk + "', " +
                            "ekonomi = '" + ekonomi + "' " +
                            "WHERE lid = " + lid;

                    idb.update(sqlUppdatera);
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna och nya länder har sparats!");

        } catch (InfException ex) {
            System.out.println("Fel vid uppdatering av länder: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte spara. Kolla så att valutan skrivs med punkt (t.ex. 10.5).");        
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AdminLänder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyttLand;
    private javax.swing.JButton btnSpara;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLander;
    // End of variables declaration//GEN-END:variables

}
