/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nikla
 */
public class AdminHållbarhetsmål extends javax.swing.JFrame {
    private InfDB idb;
    private boolean arAdmin;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminHållbarhetsmål.class.getName());

    /**
     * Creates new form AdminHållbarhetsmål
     */
    public AdminHållbarhetsmål(InfDB idb, boolean arAdmin) {
        this.idb = idb;
        this.arAdmin = arAdmin;
        initComponents();
        
        fyllTabell();
    }

    private void fyllTabell() {
        String[] kolumnNamn = {"ID", "Namn", "Beskrivning", "Prioritet"};
        
    
    
    DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return arAdmin; // true om admin, false om handläggare
            }
        };
    //
    adminHållbarhetsmål.setModel(model);
    //
    try {
            String sqlFraga = "SELECT * FROM hallbarhetsmal";
            ArrayList<HashMap<String, String>> allaMal = idb.fetchRows(sqlFraga);
            
            if (allaMal != null) {
                for (HashMap<String, String> rad : allaMal) {
                    
                    // Hämta värdena med exakt samma namn som i databas-kolumnerna
                    String[] dataRad = {
                        rad.get("hid"), 
                        rad.get("namn"), 
                        rad.get("beskrivning"), 
                        rad.get("prioritet") 
                    };
                    model.addRow(dataRad);
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av hållbarhetsmål: " + ex.getMessage());
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminHållbarhetsmål = new javax.swing.JTable();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        adminHållbarhetsmål.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "hid", "Namn", "Beskrivning", "Prioritet"
            }
        ));
        jScrollPane1.setViewportView(adminHållbarhetsmål);

        btnSpara.setText("Spara Ändring");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSpara))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        if (adminHållbarhetsmål.isEditing()) {
            adminHållbarhetsmål.getCellEditor().stopCellEditing();
        }
        DefaultTableModel model = (DefaultTableModel) adminHållbarhetsmål.getModel();
        int antalRader = model.getRowCount();

        try {
            for (int i = 0; i < antalRader; i++) {
                
                String hid = model.getValueAt(i, 0).toString();
                String namn = model.getValueAt(i, 1).toString();
                String malnummer = model.getValueAt(i, 2).toString();
                String beskrivning = model.getValueAt(i, 3).toString();
                String prioritet = model.getValueAt(i, 4).toString();

                String sqlUppdatera = "UPDATE hallbarhetsmal SET " +
                        "namn = '" + namn + "', " +
                        "malnummer = '" + malnummer + "', " +
                        "beskrivning = '" + beskrivning + "', " +
                        "prioritet = '" + prioritet + "' " +
                        "WHERE hid = " + hid;

                idb.update(sqlUppdatera);
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna av hållbarhetsmålen har sparats!");

        } catch (InfException ex) {
            System.out.println("Fel vid uppdatering av hållbarhetsmål: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod när ändringarna skulle sparas.");
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(() -> new AdminHållbarhetsmål().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminHållbarhetsmål;
    private javax.swing.JButton btnSpara;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
