/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nikla
 */
public class HandläggareProjekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandläggareProjekt.class.getName());
    private InfDB idb;
    private String pid;
    private ArrayList<String> bortagnaAid = new ArrayList<>();
    
    /**
     * Creates new form HandläggareProjekt
     */
    public HandläggareProjekt(InfDB idb, String pid) {
        this.idb = idb;
        this.pid = pid;
        
        initComponents();
        
        fyllHandläggare();
    }
    
    //Fyll i tabellen som visar vilka handläggare som arbetar på projektet som valdes
    private void fyllHandläggare()
    {
        try 
        {
            String sql =
            "SELECT a.aid, a.fornamn, a.efternamn " + "FROM anstalld a " +
            "JOIN ans_proj ap ON a.aid = ap.aid " + "WHERE ap.pid = " + pid;

            ArrayList<HashMap<String, String>> personer = idb.fetchRows(sql);

            String[] kolumner = {"ID", "Förnamn", "Efternamn"};
        
            // Skrivskydda alla kolumner utom ID (som man fyller i för att lägga till)
            DefaultTableModel model = new DefaultTableModel(kolumner, 0) 
            {
                @Override
                public boolean isCellEditable(int row, int column) 
                {
                    return false; // Inga celler kan redigeras - man lägger till/tar bort via knappar
                }
            };
            tblHandläggare.setModel(model);

            for (HashMap<String, String> person : personer)
            {
                model.addRow(new Object[]{
                person.get("aid"),
                person.get("fornamn"),
                person.get("efternamn")
                });
            }
        }
        catch (InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHandläggare = new javax.swing.JTable();
        btnLäggTill = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblHandläggare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHandläggare);

        btnLäggTill.setText("Lägg till");
        btnLäggTill.addActionListener(this::btnLäggTillActionPerformed);

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTaBort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLäggTill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpara)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLäggTill, btnTaBort});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLäggTill)
                    .addComponent(btnTaBort)
                    .addComponent(btnSpara))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Lägg till en rad för att lägga till handläggare
    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
         // Be användaren skriva in handläggarens aid
        String aidAttLaggaTill = javax.swing.JOptionPane.showInputDialog(this, "Skriv in ID-numret på handläggaren som ska läggas till:");
    
        // Om användaren tryckte avbryt eller skrev tomt - gör inget
        if (aidAttLaggaTill == null || aidAttLaggaTill.isEmpty()) 
        {
            return;
        }
    
        // Validera att det bara är siffror
        if (!Validering.arEnbartSiffror(aidAttLaggaTill)) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "ID måste vara ett nummer.");
            return;
        }
    
        try 
        {
            // Kolla att personen finns i handlaggare-tabellen
            String sqlKolla = "SELECT aid FROM handlaggare WHERE aid = " + aidAttLaggaTill;
            String finns = idb.fetchSingle(sqlKolla);
            if (finns == null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Personen med ID " + aidAttLaggaTill + " är inte en handläggare.");
                return;
            }
        
            // Kolla att personen inte redan är tilldelad projektet
            String sqlRedan = "SELECT aid FROM ans_proj WHERE pid = " + pid + " AND aid = " + aidAttLaggaTill;
            String redan = idb.fetchSingle(sqlRedan);
            if (redan != null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Handläggaren är redan tilldelad detta projekt.");
                return;
            }
        
            // Hämta namn och lägg till i tabellen
            String sqlNamn = "SELECT fornamn, efternamn FROM anstalld WHERE aid = " + aidAttLaggaTill;
            HashMap<String, String> person = idb.fetchRow(sqlNamn);
        
            DefaultTableModel model = (DefaultTableModel) tblHandläggare.getModel();
            model.addRow(new Object[]{
                aidAttLaggaTill,
                person.get("fornamn"),
                person.get("efternamn")
            });
        
        } 
        catch (InfException ex) 
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnLäggTillActionPerformed

    //Tar bort den markerade raden
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        int valdRad = tblHandläggare.getSelectedRow();
    
        if (valdRad == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Markera en handläggare att ta bort först.");
            return;
        }
    
        DefaultTableModel model = (DefaultTableModel) tblHandläggare.getModel();
    
        // Spara aid:t i listan över borttagna
        String aidAttTaBort = model.getValueAt(valdRad, 0).toString();
        bortagnaAid.add(aidAttTaBort);
    
        model.removeRow(valdRad);
    }//GEN-LAST:event_btnTaBortActionPerformed

    //Sparar eventuella ändringar som har gjorts till tabellen
    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try 
        {
            // Först - radera alla som markerats för borttagning
            for (String aidAttTaBort : bortagnaAid) 
            {
                String sqlTaBort = "DELETE FROM ans_proj WHERE pid = " + pid + " AND aid = " + aidAttTaBort;
                idb.delete(sqlTaBort);
            }
            bortagnaAid.clear();
        
            // Sedan - lägg till alla i tabellen som inte redan finns i databasen
            DefaultTableModel model = (DefaultTableModel) tblHandläggare.getModel();
            for (int i = 0; i < model.getRowCount(); i++) 
            {
                String aidIRad = model.getValueAt(i, 0).toString();
            
                // Kolla om kopplingen redan finns i databasen
                String sqlKolla = "SELECT aid FROM ans_proj WHERE pid = " + pid + " AND aid = " + aidIRad;
                String finns = idb.fetchSingle(sqlKolla);
            
                // Finns den inte, lägg till
                if (finns == null) 
                {
                    String sqlNy = "INSERT INTO ans_proj (pid, aid) VALUES (" + pid + ", " + aidIRad + ")";
                    idb.insert(sqlNy);
                }
            }
        
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna har sparats!");
            fyllHandläggare();
        
        } 
        catch (InfException ex) 
        {
            System.out.println(ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod vid sparande.");
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new HandläggareProjekt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHandläggare;
    // End of variables declaration//GEN-END:variables
}
