/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikla
 */
public class Hållbarhetsmål extends javax.swing.JFrame {
    private InfDB idb;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName());

    /**
     * Creates new form Hållbarhetsmål
     */
    public Hållbarhetsmål(InfDB idb) {
        this.idb = idb;
       
        initComponents();
        
        fyllTabell();
        tblHållbarhetsmål.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        var colModel = tblHållbarhetsmål.getColumnModel();

        colModel.getColumn(0).setPreferredWidth(75);
        colModel.getColumn(1).setPreferredWidth(300);
        colModel.getColumn(2).setPreferredWidth(1000);
        colModel.getColumn(3).setPreferredWidth(75);
    }

    private void fyllTabell() 
    {
        String[] kolumnNamn = {"Nummer", "Namn", "Beskrivning", "Prioritet"};
        DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0);
        
        tblHållbarhetsmål.setModel(model);
        
        try {
            String mål = "SELECT malnummer, namn, beskrivning, prioritet FROM hallbarhetsmal";
            java.util.ArrayList<java.util.HashMap<String, String>> allaMål = idb.fetchRows(mål);
            
            if (allaMål != null){
                for (java.util.HashMap<String, String> rad : allaMål) {
                    
                    String[] dataRad = {
                        rad.get("malnummer"),
                        rad.get("namn"),
                        rad.get("beskrivning"),
                        rad.get("prioritet")
                    };
                    model.addRow(dataRad);
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av hållbarhetsmål: " + ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHållbarhetsmål = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblHållbarhetsmål.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nummer", "Namn", "Beskrivning", "Prioritet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHållbarhetsmål.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblHållbarhetsmål);
        if (tblHållbarhetsmål.getColumnModel().getColumnCount() > 0) {
            tblHållbarhetsmål.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1453, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new Hållbarhetsmål().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHållbarhetsmål;
    // End of variables declaration//GEN-END:variables
}
