/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author jowe2
 */
public class Meny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());

    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
        
        try{
            //hämta aid från användare
            String sqlAid = "SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String aid = idb.fetchSingle(sqlAid);
            
            //kolla om användaren är admin
            String sqlAdmin = "SELECT aid FROM admin WHERE aid = " + aid;
            String behorighetsniva = idb.fetchSingle(sqlAdmin);
            
            if(behorighetsniva.equals("1")){
                lblRoll.setText("Administratör");
            } else{
                lblRoll.setText("Handläggare");
            }
            
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        btnMinaProjekt = new javax.swing.JButton();
        btnPartners = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnAndraUppgifter = new javax.swing.JButton();
        lblRoll = new javax.swing.JLabel();
        lblHantera = new javax.swing.JLabel();
        btnProjekt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("jLabel1");

        btnMinaProjekt.setText("Mina Projekt");
        btnMinaProjekt.addActionListener(this::btnMinaProjektActionPerformed);

        btnPartners.setText("Partners");

        btnPersonal.setText("Personal");

        btnAndraUppgifter.setText("Ändra uppgifter");

        lblRoll.setText("jLabel1");

        lblHantera.setText("Hantera");

        btnProjekt.setText("Projekt");

        jButton1.setText("Anställda");

        jButton2.setText("Avdelningar");

        jButton3.setText("Partners");

        jButton4.setText("Länder");

        jButton5.setText("Hållbarhetsmål");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAndraUppgifter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPartners, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblHantera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(lblRoll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInloggadAnvandare)
                    .addComponent(lblRoll))
                .addGap(18, 18, 18)
                .addComponent(btnMinaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAndraUppgifter)
                .addGap(52, 52, 52)
                .addComponent(lblHantera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjekt)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        // TODO add your handling code here:
        try {
    // hämtar från sql
    String sqlFraga = "SELECT projekt.projektnamn " +
                      "FROM projekt " +
                      "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                      "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
                      "WHERE anstalld.epost = '" + inloggadAnvandare + "'";

    // 2. Vi ber databasen hämta kolumn med alla projektnamn
    java.util.ArrayList<String> projektLista = idb.fetchColumn(sqlFraga);

    // 3. Vi kollar om vi fick något svar från databasen
    if (projektLista != null && !projektLista.isEmpty()) {
        //
        String allaProjekt = String.join(", ", projektLista);
        
        //
        javax.swing.JOptionPane.showMessageDialog(this, "Du är med i följande projekt: " + allaProjekt);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Du är inte tilldelad några projekt för tillfället.");
    }

} catch (oru.inf.InfException ex) {
    // felmeddelande
    javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + ex.getMessage());
}
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Meny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifter;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lblHantera;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblRoll;
    // End of variables declaration//GEN-END:variables
}
