/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author jowe2
 */
public class Meny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private String aid;
    private boolean arAdmin = false; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());

    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
        
        try{
            //hämta aid från användare
            String sqlAid = "SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            aid = idb.fetchSingle(sqlAid);
            
            //kolla om användaren är admin
            String sqlAdmin = "SELECT aid FROM admin WHERE aid = " + aid;
            String behorighetsniva = idb.fetchSingle(sqlAdmin);
            
            if(behorighetsniva.equals("1")){
                lblRoll.setText("Administratör");
                arAdmin = true;
                
            } else{
                lblRoll.setText("Handläggare");
                lblHantera.setVisible(false);
                btnProjekt.setVisible(false);
                btnAnställda.setVisible(false);
                btnAvdelningar.setVisible(false);
                btnHanteraPartners.setVisible(false);
                btnLänder.setVisible(false);
                btnHanteraHållbarhetsmål.setVisible(false);
            }
            
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        btnMinaProjekt = new javax.swing.JButton();
        btnPartners = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnAndraUppgifter = new javax.swing.JButton();
        btnAvdelningensProjekt = new javax.swing.JButton();
        btnHållbarhetsmål = new javax.swing.JButton();
        lblRoll = new javax.swing.JLabel();
        lblHantera = new javax.swing.JLabel();
        btnProjekt = new javax.swing.JButton();
        btnAnställda = new javax.swing.JButton();
        btnAvdelningar = new javax.swing.JButton();
        btnHanteraPartners = new javax.swing.JButton();
        btnLänder = new javax.swing.JButton();
        btnHanteraHållbarhetsmål = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("jLabel1");

        btnMinaProjekt.setText("Mina Projekt");
        btnMinaProjekt.addActionListener(this::btnMinaProjektActionPerformed);

        btnPartners.setText("Partners");
        btnPartners.addActionListener(this::btnPartnersActionPerformed);

        btnPersonal.setText("Personal");
        btnPersonal.addActionListener(this::btnPersonalActionPerformed);

        btnAndraUppgifter.setText("Ändra uppgifter");
        btnAndraUppgifter.addActionListener(this::btnAndraUppgifterActionPerformed);

        btnAvdelningensProjekt.setText("Avdelningens Projekt");
        btnAvdelningensProjekt.addActionListener(this::btnAvdelningensProjektActionPerformed);

        btnHållbarhetsmål.setText("Hållbarhetsmål");
        btnHållbarhetsmål.addActionListener(this::btnHållbarhetsmålActionPerformed);

        lblRoll.setText("jLabel1");

        lblHantera.setText("Hantera");

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(this::btnProjektActionPerformed);

        btnAnställda.setText("Anställda");
        btnAnställda.addActionListener(this::btnAnställdaActionPerformed);

        btnAvdelningar.setText("Avdelningar");
        btnAvdelningar.addActionListener(this::btnAvdelningarActionPerformed);

        btnHanteraPartners.setText("Partners");
        btnHanteraPartners.addActionListener(this::btnHanteraPartnersActionPerformed);

        btnLänder.setText("Länder");
        btnLänder.addActionListener(this::btnLänderActionPerformed);

        btnHanteraHållbarhetsmål.setText("Hållbarhetsmål");
        btnHanteraHållbarhetsmål.addActionListener(this::btnHanteraHållbarhetsmålActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHantera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRoll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInloggadAnvandare)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAvdelningar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAvdelningensProjekt)
                                    .addComponent(btnMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPartners, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnHanteraPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAnställda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHanteraHållbarhetsmål, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLänder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAndraUppgifter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHållbarhetsmål, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAndraUppgifter, btnAnställda, btnAvdelningar, btnAvdelningensProjekt, btnHanteraHållbarhetsmål, btnHanteraPartners, btnHållbarhetsmål, btnLänder, btnMinaProjekt, btnPartners, btnPersonal, btnProjekt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInloggadAnvandare)
                    .addComponent(lblRoll))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHållbarhetsmål)
                    .addComponent(btnPartners)
                    .addComponent(btnMinaProjekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvdelningensProjekt)
                    .addComponent(btnPersonal)
                    .addComponent(btnAndraUppgifter))
                .addGap(110, 110, 110)
                .addComponent(lblHantera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjekt)
                    .addComponent(btnLänder)
                    .addComponent(btnHanteraPartners))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvdelningar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnställda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHanteraHållbarhetsmål, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersActionPerformed
        // TODO add your handling code here:
        Partner partner = new Partner(idb, arAdmin);
        partner.setVisible(true);
    }//GEN-LAST:event_btnPartnersActionPerformed

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        // TODO add your handling code here:
        MinaProjekt minaProjekt = new MinaProjekt(idb, aid);
        minaProjekt.setVisible(true);

    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnHållbarhetsmålActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHållbarhetsmålActionPerformed
        // TODO add your handling code here:
        Hållbarhetsmål mål = new Hållbarhetsmål();
        mål.setVisible(true);
    }//GEN-LAST:event_btnHållbarhetsmålActionPerformed

    private void btnAvdelningensProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningensProjektActionPerformed
        // TODO add your handling code here:
        AvdelningensProjekt avdProjekt = new AvdelningensProjekt();
        avdProjekt.setVisible(true);
    }//GEN-LAST:event_btnAvdelningensProjektActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        Personal personal = new Personal();
        personal.setVisible(true);
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnAndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterActionPerformed
        // TODO add your handling code here:
        ÄndraUppgifter uppgifter = new ÄndraUppgifter();
        uppgifter.setVisible(true);
    }//GEN-LAST:event_btnAndraUppgifterActionPerformed

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
        // TODO add your handling code here:
        AdminProjekt adminProjekt = new AdminProjekt();
        adminProjekt.setVisible(true);
    }//GEN-LAST:event_btnProjektActionPerformed

    private void btnHanteraPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraPartnersActionPerformed
        // TODO add your handling code here:
        AdminPartners adminPartners = new AdminPartners();
        adminPartners.setVisible(true);
    }//GEN-LAST:event_btnHanteraPartnersActionPerformed

    private void btnLänderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLänderActionPerformed
        // TODO add your handling code here:
        AdminLänder adminLänder = new AdminLänder();
        adminLänder.setVisible(true);
    }//GEN-LAST:event_btnLänderActionPerformed

    private void btnAvdelningarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningarActionPerformed
        // TODO add your handling code here:
        AdminLänder adminLänder = new AdminLänder();
        adminLänder.setVisible(true);
    }//GEN-LAST:event_btnAvdelningarActionPerformed

    private void btnAnställdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnställdaActionPerformed
        // TODO add your handling code here:
        AdminAnställda adminAnställda = new AdminAnställda();
        adminAnställda.setVisible(true);
    }//GEN-LAST:event_btnAnställdaActionPerformed

    private void btnHanteraHållbarhetsmålActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraHållbarhetsmålActionPerformed
        // TODO add your handling code here:
        AdminHållbarhetsmål adminMål = new AdminHållbarhetsmål(idb, arAdmin);
        adminMål.setVisible(true);
    }//GEN-LAST:event_btnHanteraHållbarhetsmålActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Meny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifter;
    private javax.swing.JButton btnAnställda;
    private javax.swing.JButton btnAvdelningar;
    private javax.swing.JButton btnAvdelningensProjekt;
    private javax.swing.JButton btnHanteraHållbarhetsmål;
    private javax.swing.JButton btnHanteraPartners;
    private javax.swing.JButton btnHållbarhetsmål;
    private javax.swing.JButton btnLänder;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JLabel lblHantera;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblRoll;
    // End of variables declaration//GEN-END:variables
}
