/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class Partner extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Partner.class.getName());

    /**
     * Creates new form Partner
     */
    public Partner(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        
        fyllTabell(); 
    }
    
    private void fyllTabell() {

        String[] kolumnNamn = {"ID", "Namn", "Kontaktperson", "E-post", "Telefon", "Adress", "Bransch", "Stad", "land"};
        
        DefaultTableModel model = new DefaultTableModel(kolumnNamn, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblPartners.setModel(model);
        try {
            String sqlFraga = "SELECT DISTINCT partner.* FROM partner " +
                              "JOIN projekt_partner ON partner.pid = projekt_partner.partner_pid " +
                              "JOIN ans_proj ON projekt_partner.pid = ans_proj.pid " +
                              "WHERE ans_proj.aid = " + aid;
            
            ArrayList<HashMap<String, String>> relevantaPartners = idb.fetchRows(sqlFraga);
            
if (relevantaPartners != null) {
                for (HashMap<String, String> rad : relevantaPartners) {
                    
                    String stadId = rad.get("stad"); 
                    String stadNamn = "";
                    String landNamn = "";
                    
                    if(stadId != null) {
                        String sqlStad = "SELECT namn FROM stad WHERE sid = " + stadId;
                        stadNamn = idb.fetchSingle(sqlStad);
                        
                        String sqlStadLandID = "SELECT land FROM stad WHERE sid = " + stadId;
                        String landId = idb.fetchSingle(sqlStadLandID);
                        
                        if(landId != null) {
                            String sqlLand = "SELECT namn FROM land WHERE lid = " + landId;
                            landNamn = idb.fetchSingle(sqlLand);
                        }
                    }

                   
                    String[] dataRad = {
                        rad.get("pid"), 
                        rad.get("namn"), 
                        rad.get("kontaktperson"), 
                        rad.get("kontaktepost"), 
                        rad.get("telefon"), 
                        rad.get("adress"), 
                        rad.get("branch"), 
                        stadNamn,                 
                        landNamn                  
                    };
                    
                    model.addRow(dataRad);
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av relevanta partners: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartners = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pid", "Namn", "Kontaktperson", "E-post", "Telefonnummer", "Adress", "Branch", "Stad", "land"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPartners);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     //   java.awt.EventQueue.invokeLater(() -> new Partner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartners;
    // End of variables declaration//GEN-END:variables
}
