/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nikla
 */
public class PartnerProjekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PartnerProjekt.class.getName());
    private InfDB idb;
    private String pid;
    private ArrayList<String> bortagnaPartnerPid = new ArrayList<>();
    /**
     * Creates new form PartnerProjekt
     */
    public PartnerProjekt(InfDB idb, String pid ) {
        this.idb = idb;
        this.pid = pid;
        
        initComponents();
        
        fyllPartner();
    }

    //Fyll i tabellen som visar vilka partners som arbetar på projektet som valdes
    private void fyllPartner()
    {
        try 
        {
            // Hämta alla partners kopplade till projektet
            String sql =
            "SELECT p.pid, p.namn " + 
            "FROM partner p " +
            "JOIN projekt_partner pp ON p.pid = pp.partner_pid " +
            "WHERE pp.pid = " + pid;

            ArrayList<HashMap<String, String>> partners = idb.fetchRows(sql);

            String[] kolumner = {"ID", "Namn"};
            // Skrivskydda alla celler - man lägger till/tar bort via knappar
            DefaultTableModel model = new DefaultTableModel(kolumner, 0) 
            {
                @Override
                public boolean isCellEditable(int row, int column) 
                {
                    return false;
                }
            };
            tblPartner.setModel(model);

            for (HashMap<String, String> partner : partners)
            {
                model.addRow(new Object[]{
                    partner.get("pid"),
                    partner.get("namn")
                });
            }
        }
        catch (InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartner = new javax.swing.JTable();
        btnLäggTill = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPartner);

        btnLäggTill.setText("Lägg till");
        btnLäggTill.addActionListener(this::btnLäggTillActionPerformed);

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTaBort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLäggTill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpara))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnLäggTill)
                    .addComponent(btnTaBort))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Lägg till en rad för att lägga till partner
    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        // Be användaren skriva in partnerns ID
        String partnerPidAttLaggaTill = javax.swing.JOptionPane.showInputDialog(this, "Skriv in ID-numret på partnern som ska läggas till:");
    
        // Om användaren tryckte avbryt eller skrev tomt - gör inget
        if (partnerPidAttLaggaTill == null || partnerPidAttLaggaTill.isEmpty()) 
        {
            return;
        }
    
        // Validera att det bara är siffror
        if (!Validering.arEnbartSiffror(partnerPidAttLaggaTill)) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "ID måste vara ett nummer.");
            return;
        }
    
        try 
        {
            // Kolla att partnern finns i partner-tabellen
            String sqlKolla = "SELECT pid FROM partner WHERE pid = " + partnerPidAttLaggaTill;
            String finns = idb.fetchSingle(sqlKolla);
            if (finns == null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Det finns ingen partner med ID " + partnerPidAttLaggaTill + ".");
                return;
            }
        
            // Kolla att partnern inte redan är tilldelad projektet
            String sqlRedan = "SELECT partner_pid FROM projekt_partner WHERE pid = " + pid + " AND partner_pid = " + partnerPidAttLaggaTill;
            String redan = idb.fetchSingle(sqlRedan);
            if (redan != null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Partnern är redan tilldelad detta projekt.");
                return;
            }
        
            // Hämta partnerns namn och lägg till i tabellen
            String sqlNamn = "SELECT namn FROM partner WHERE pid = " + partnerPidAttLaggaTill;
            String namn = idb.fetchSingle(sqlNamn);
        
            DefaultTableModel model = (DefaultTableModel) tblPartner.getModel();
            model.addRow(new Object[]{
                partnerPidAttLaggaTill,
                namn
            });        
        } 
        catch (InfException ex) 
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnLäggTillActionPerformed

    //Tar bort den markerade raden
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        int valdRad = tblPartner.getSelectedRow();
    
        if (valdRad == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Markera en partner att ta bort först.");
            return;
        }
    
        DefaultTableModel model = (DefaultTableModel) tblPartner.getModel();
    
        // Spara partner-pid i listan över borttagna
        String partnerPidAttTaBort = model.getValueAt(valdRad, 0).toString();
        bortagnaPartnerPid.add(partnerPidAttTaBort);
    
        model.removeRow(valdRad);
    }//GEN-LAST:event_btnTaBortActionPerformed

    //Sparar eventuella ändringar som har gjorts till tabellen
    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try 
        {
            // Först - radera alla som markerats för borttagning
            for (String partnerPidAttTaBort : bortagnaPartnerPid) 
            {
                String sqlTaBort = "DELETE FROM projekt_partner WHERE pid = " + pid + " AND partner_pid = " + partnerPidAttTaBort;
                idb.delete(sqlTaBort);
            }
            bortagnaPartnerPid.clear();
        
            // Sedan - lägg till alla i tabellen som inte redan finns i databasen
            DefaultTableModel model = (DefaultTableModel) tblPartner.getModel();
            for (int i = 0; i < model.getRowCount(); i++) 
            {
                String partnerPidIRad = model.getValueAt(i, 0).toString();
            
                // Kolla om kopplingen redan finns i databasen
                String sqlKolla = "SELECT partner_pid FROM projekt_partner WHERE pid = " + pid + " AND partner_pid = " + partnerPidIRad;
                String finns = idb.fetchSingle(sqlKolla);
            
                // Finns den inte, lägg till
                if (finns == null) 
                {
                    String sqlNy = "INSERT INTO projekt_partner (pid, partner_pid) VALUES (" + pid + ", " + partnerPidIRad + ")";
                    idb.insert(sqlNy);
                }
            }
        
            javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna har sparats!");
            fyllPartner();
        } 
        catch (InfException ex) 
        {
            System.out.println(ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod vid sparande.");
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PartnerProjekt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartner;
    // End of variables declaration//GEN-END:variables
}
