/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author David
 */
public class Partner extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Partner.class.getName());
    
   private void laddaPartners() {
    try {
        // 1. Vi hämtar FLER kolumner från databasen så vi har något att fylla tabellen med
        String sql = "SELECT partner.pid, partner.namn, partner.telefon, partner.kontaktpost FROM partner " +
                     "JOIN projekt_partner ON partner.pid = projekt_partner.partner_id " +
                     "JOIN projekt ON projekt_partner.pid = projekt.pid " +
                     "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                     "WHERE ans_proj.aid = " + aid;

        // 2. Vi använder fetchRows precis som Niklas!
        java.util.ArrayList<java.util.HashMap<String, String>> partnerData = idb.fetchRows(sql);

        // 3. Vi skapar rubrikerna till dina kolumner
        String[] kolumner = {"ID", "Partnernamn", "Telefon", "E-post"};

        if (partnerData != null && !partnerData.isEmpty()) {
            // 4. Vi förbereder matrisen (antal rader utifrån svaret, och 4 kolumner)
            String[][] data = new String[partnerData.size()][4];

            // 5. Loopen som hämtar datan från databasen och lägger i tabellen (Exakt som Niklas!)
            for (int i = 0; i < partnerData.size(); i++) {
                data[i][0] = partnerData.get(i).get("pid");
                data[i][1] = partnerData.get(i).get("namn");
                data[i][2] = partnerData.get(i).get("telefon");
                data[i][3] = partnerData.get(i).get("kontaktpost");
            }

            // 6. Vi trycker in all data i er tabell (Se till att er tabell heter tblPartners i designläget!)
            tblPartners.setModel(new javax.swing.table.DefaultTableModel(data, kolumner));
        }

    } catch (InfException ex) {
        System.out.println(ex.getMessage());
    }
} 

    /**
     * Creates new form Partner
     */
    public Partner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartners = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPartners);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Partner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartners;
    // End of variables declaration//GEN-END:variables
}
